# Generated by Django 3.2.9 on 2021-12-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20211227_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
                ('image_abt', models.ImageField(null=True, upload_to='admin_pics')),
            ],
            options={
                'verbose_name_plural': 'AboutUs',
            },
        ),
    ]
