# Generated by Django 3.2.9 on 2021-12-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AddField(
            model_name='about',
            name='achieve',
            field=models.TextField(blank=True),
        ),
    ]
