# Generated by Django 3.2.9 on 2021-12-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20211230_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
