# Generated by Django 3.2.9 on 2021-12-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
