# Generated by Django 3.2.9 on 2022-01-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='support',
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
