# Generated by Django 3.2.9 on 2022-03-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20220104_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='achieve',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_2',
        ),
    ]
