# Generated by Django 3.2.9 on 2021-11-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tutor',
            field=models.ImageField(blank=True, null=True, upload_to='course_tutor'),
        ),
    ]
