# Generated by Django 3.2.9 on 2021-12-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211222_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='content_file',
        ),
    ]
