# Generated by Django 3.2.9 on 2021-11-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tutor_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
