# Generated by Django 3.2.9 on 2021-11-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courses_tutor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tutor_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_tutor'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='tutor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
